// <auto-generated />
using System;
using InsuranceAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceAPI.Migrations
{
    [DbContext(typeof(InsuranceDbContext))]
    [Migration("20250926063132_AddInsuranceTypeIdToPolicy")]
    partial class AddInsuranceTypeIdToPolicy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsuranceAPI.Models.Agent", b =>
                {
                    b.Property<int>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Agent_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgentId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AgentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Agent_Code");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    b.HasKey("AgentId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[User_Id] IS NOT NULL");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("InsuranceAPI.Models.Claim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Claim_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimId"));

                    b.Property<int?>("AgentId")
                        .HasColumnType("int")
                        .HasColumnName("Agent_Id");

                    b.Property<decimal?>("ApprovedAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Approved_Amount");

                    b.Property<decimal?>("ClaimAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Claim_Amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Created_At");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("Created_By_User_Id");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("Customer_Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("EstimatedResolutionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Estimated_Resolution_Date");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Incident_Date");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("Policy_Id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Processed_At");

                    b.Property<int?>("ProcessedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("Processed_By_User_Id");

                    b.Property<DateTime>("ReportedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Reported_Date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Updated_At");

                    b.HasKey("ClaimId");

                    b.HasIndex("AgentId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("ProcessedByUserId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("InsuranceAPI.Models.Coverage", b =>
                {
                    b.Property<int>("CoverageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Coverage_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoverageId"));

                    b.Property<decimal>("BasePremium")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Base_Premium");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Created_At");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("InsuranceTypeId")
                        .HasColumnType("int")
                        .HasColumnName("Insurance_Type_Id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit");

                    b.Property<decimal>("Limit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Premium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Updated_At");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    b.HasKey("CoverageId");

                    b.HasIndex("InsuranceTypeId");

                    b.ToTable("Coverages");
                });

            modelBuilder.Entity("InsuranceAPI.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Customer_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IdNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Id_No");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[User_Id] IS NOT NULL");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("InsuranceAPI.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Document_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ClaimId")
                        .HasColumnType("int")
                        .HasColumnName("Claim_Id");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("Customer_Id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Expires_At");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("File_Type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("File_Url");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("Policy_Id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Updated_At");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Uploaded_At");

                    b.Property<int?>("UploadedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("Uploaded_By_User_Id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DocumentId");

                    b.HasIndex("ClaimId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("InsuranceAPI.Models.InsuranceType", b =>
                {
                    b.Property<int>("InsuranceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Ins_Type_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsuranceTypeId"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CoverageDetails")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Coverage_Details");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Created_At");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Updated_At");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    b.Property<int>("ValidityPeriodDays")
                        .HasColumnType("int")
                        .HasColumnName("Validity_Period_Days");

                    b.HasKey("InsuranceTypeId");

                    b.ToTable("InsuranceTypes");
                });

            modelBuilder.Entity("InsuranceAPI.Models.Offer", b =>
                {
                    b.Property<int>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Offer_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfferId"));

                    b.Property<string>("AdditionalData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Additional_Data");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Admin_Notes");

                    b.Property<int?>("AgentId")
                        .HasColumnType("int")
                        .HasColumnName("Agent_Id");

                    b.Property<string>("AgentNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Agent_Notes");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Approved_At");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Base_Price");

                    b.Property<decimal?>("CoverageAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Coverage_Amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Created_At");

                    b.Property<string>("CustomerAdditionalInfo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Customer_Additional_Info");

                    b.Property<DateTime?>("CustomerApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Customer_Approved_At");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("Customer_Id");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Discount_Rate");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Final_Price");

                    b.Property<int?>("InsuranceTypeId")
                        .HasColumnType("int")
                        .HasColumnName("Insurance_Type_Id");

                    b.Property<bool>("IsCustomerApproved")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Customer_Approved");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Processed_At");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Rejection_Reason");

                    b.Property<DateTime?>("RequestedStartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Requested_Start_Date");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Reviewed_At");

                    b.Property<int?>("ReviewedByAgentId")
                        .HasColumnType("int")
                        .HasColumnName("Reviewed_By_Agent_Id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Updated_At");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("datetime2")
                        .HasColumnName("Valid_Until");

                    b.HasKey("OfferId");

                    b.HasIndex("AgentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InsuranceTypeId");

                    b.HasIndex("ReviewedByAgentId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("InsuranceAPI.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Payment_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Created_At");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Paid_At");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("Policy_Id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Updated_At");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    b.HasKey("PaymentId");

                    b.HasIndex("PolicyId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("InsuranceAPI.Models.Policy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Policy_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Created_At");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("End_Date");

                    b.Property<int?>("InsuranceTypeId")
                        .HasColumnType("int")
                        .HasColumnName("Ins_Type_Id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OfferId")
                        .HasColumnType("int")
                        .HasColumnName("Offer_Id");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Policy_Number");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Start_Date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalPremium")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total_Premium");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Updated_At");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    b.HasKey("PolicyId");

                    b.HasIndex("InsuranceTypeId");

                    b.HasIndex("OfferId");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("InsuranceAPI.Models.SelectedCoverage", b =>
                {
                    b.Property<int>("SelectedCoverageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Sel_Cov_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SelectedCoverageId"));

                    b.Property<int?>("CoverageId")
                        .HasColumnType("int")
                        .HasColumnName("Coverage_Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Created_At");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OfferId")
                        .HasColumnType("int")
                        .HasColumnName("Offer_Id");

                    b.Property<decimal>("Premium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SelectedLimit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Selected_Limit");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    b.HasKey("SelectedCoverageId");

                    b.HasIndex("CoverageId");

                    b.HasIndex("OfferId");

                    b.ToTable("SelectedCoverages");
                });

            modelBuilder.Entity("InsuranceAPI.Models.TokenBlacklist", b =>
                {
                    b.Property<int>("TokenBlacklistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Token_black_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenBlacklistId"));

                    b.Property<DateTime>("BlacklistedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Blacklisted_At");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Created_At");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Expires_At");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("User_Email");

                    b.HasKey("TokenBlacklistId");

                    b.ToTable("TokenBlacklist");
                });

            modelBuilder.Entity("InsuranceAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Created_At");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password_Hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InsuranceAPI.Models.Agent", b =>
                {
                    b.HasOne("InsuranceAPI.Models.User", "User")
                        .WithOne("Agent")
                        .HasForeignKey("InsuranceAPI.Models.Agent", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceAPI.Models.Claim", b =>
                {
                    b.HasOne("InsuranceAPI.Models.Agent", "Agent")
                        .WithMany("Claims")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InsuranceAPI.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("InsuranceAPI.Models.Customer", "Customer")
                        .WithMany("Claims")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InsuranceAPI.Models.Policy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InsuranceAPI.Models.User", "ProcessedByUser")
                        .WithMany()
                        .HasForeignKey("ProcessedByUserId");

                    b.Navigation("Agent");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("Policy");

                    b.Navigation("ProcessedByUser");
                });

            modelBuilder.Entity("InsuranceAPI.Models.Coverage", b =>
                {
                    b.HasOne("InsuranceAPI.Models.InsuranceType", "InsuranceType")
                        .WithMany("Coverages")
                        .HasForeignKey("InsuranceTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("InsuranceType");
                });

            modelBuilder.Entity("InsuranceAPI.Models.Customer", b =>
                {
                    b.HasOne("InsuranceAPI.Models.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("InsuranceAPI.Models.Customer", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceAPI.Models.Document", b =>
                {
                    b.HasOne("InsuranceAPI.Models.Claim", "Claim")
                        .WithMany("Documents")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InsuranceAPI.Models.Customer", "Customer")
                        .WithMany("Documents")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InsuranceAPI.Models.Policy", "Policy")
                        .WithMany("Documents")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InsuranceAPI.Models.User", "UploadedByUser")
                        .WithMany("Documents")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InsuranceAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Claim");

                    b.Navigation("Customer");

                    b.Navigation("Policy");

                    b.Navigation("UploadedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceAPI.Models.Offer", b =>
                {
                    b.HasOne("InsuranceAPI.Models.Agent", "Agent")
                        .WithMany("Offers")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InsuranceAPI.Models.Customer", "Customer")
                        .WithMany("Offers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InsuranceAPI.Models.InsuranceType", "InsuranceType")
                        .WithMany("Offers")
                        .HasForeignKey("InsuranceTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InsuranceAPI.Models.Agent", "ReviewedByAgent")
                        .WithMany()
                        .HasForeignKey("ReviewedByAgentId");

                    b.Navigation("Agent");

                    b.Navigation("Customer");

                    b.Navigation("InsuranceType");

                    b.Navigation("ReviewedByAgent");
                });

            modelBuilder.Entity("InsuranceAPI.Models.Payment", b =>
                {
                    b.HasOne("InsuranceAPI.Models.Policy", "Policy")
                        .WithMany("Payments")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("InsuranceAPI.Models.Policy", b =>
                {
                    b.HasOne("InsuranceAPI.Models.InsuranceType", "InsuranceType")
                        .WithMany()
                        .HasForeignKey("InsuranceTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InsuranceAPI.Models.Offer", "Offer")
                        .WithMany("Policies")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("InsuranceType");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("InsuranceAPI.Models.SelectedCoverage", b =>
                {
                    b.HasOne("InsuranceAPI.Models.Coverage", "Coverage")
                        .WithMany("SelectedCoverages")
                        .HasForeignKey("CoverageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InsuranceAPI.Models.Offer", "Offer")
                        .WithMany("SelectedCoverages")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Coverage");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("InsuranceAPI.Models.Agent", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("InsuranceAPI.Models.Claim", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("InsuranceAPI.Models.Coverage", b =>
                {
                    b.Navigation("SelectedCoverages");
                });

            modelBuilder.Entity("InsuranceAPI.Models.Customer", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Documents");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("InsuranceAPI.Models.InsuranceType", b =>
                {
                    b.Navigation("Coverages");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("InsuranceAPI.Models.Offer", b =>
                {
                    b.Navigation("Policies");

                    b.Navigation("SelectedCoverages");
                });

            modelBuilder.Entity("InsuranceAPI.Models.Policy", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("InsuranceAPI.Models.User", b =>
                {
                    b.Navigation("Agent");

                    b.Navigation("Customer");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
